test: test.cpp appointment_hospital.o head.h
	g++ test.cpp appointment_hospital.o -o test
appointment_hospital.o: appointment_hospital.cpp head.h
	g++ -c appointment_hospital.cpp -o appointment_hospital.o