test: test.cpp local_queue.cpp appointment_hospital.cpp Fb_heap.cpp reportlist.cpp report.cpp head.h
	g++ test.cpp -o test

clear:
	rm -f *.exe
	rm -f *.o
	rm -f ./Report/*.csv
	rm -f ./Report/MonthlyReport/*.txt
	rm -f ./Report/SortedWeeklyFile/*.csv
	rm -f ./Report/WeeklyFile/*.csv

